### ISSUE TITLE
ReverseDSC 1.7.3 - MSFT_SPOutgoingEmailSettings Parameters UseTLS fails with SharePoint 2013

### ISSUE THREAD

**Issue by llowevad** [NikCharlebois/ReverseDSC#3]
When running ReverseDSC (1.7.3) in a SharePoint 2013 environment using SharePointDSC 1.8, it fails when running the MSFT_SPOutgoingEmailSettings SharePointDSC module due to a check on Get-TargetResource of that module checking if UseTLS is true as this parameter is only supported in SP2016 due to the new feature of having the ability to use Secure SMTP connections in SP2016.

It seems that because ReverseDSC creates a hashtable of all parameters UseTLS is included and since it is included it fails when it hits the check for UseTLS = true and Product Version not equal to 16.

![image](https://user-images.githubusercontent.com/8823690/29327673-ead7f682-81bd-11e7-9749-125fb7b0df8c.png)

It seems SharePointDSC 1.8 has a parameter for UseTLS (Boolean switch, not required) and does the following check:
    if (($PSBoundParameters.ContainsKey("UseTLS") -eq $true) `
        -and $installedVersion.FileMajorPart -ne 16) 
    {
        throw [Exception] "UseTLS is only supported in SharePoint 2016."
    }

Where version SharePointDSC 1.6 does not have this parameter or this check.

Thanks,
Dave

**Comment by NikCharlebois** [comment]
Thanks Dave, I will investigate ASAP

**Comment by llowevad** [comment]
I would like to add that SMTPPort has a similar check in SharePointDSC 1.8 and will throw an error when provided and using SP2013. May want to test for this scenario in the fix as well.

With this one it is checking if it exists in the provided parameters, not even looking at the value.

    if (($PSBoundParameters.ContainsKey("SMTPPort") -eq $true) `
        -and $installedVersion.FileMajorPart -ne 16) 
    {
        #throw [Exception] "SMTPPort is only supported in SharePoint 2016."
    }

Thank you,
Dave

**Comment by NikCharlebois** [comment]
Just realized that this was logged under ReverseDSC. It is actually a bug in the SharePointDSC.Reverse project. Please make sure you log issues them under the proper orchestrator (in this case SharePointDSC.Reverse). The issue has been fixed with SharePointDSC.Reverse v1.8.1.0. Thanks
